// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package server

import (
	"database/sql"
	"github.com/google/wire"
	http2 "go-rest-api-boilerplate/internal/transport/http"
	"go-rest-api-boilerplate/internal/usecase/repository"
	"go-rest-api-boilerplate/internal/usecase/service"
	"net/http"
)

// Injectors from wire.go:

func InitializedHandlerServer(db *sql.DB) http.Handler {
	userRepository := repository.NewUserRepository(db)
	userService := service.NewUserService(userRepository)
	handler := http2.NewHandler(userService)
	return handler
}

// wire.go:

var userSet = wire.NewSet(repository.NewUserRepository, service.NewUserService)
